import io
import logging
import os
from dotenv import load_dotenv
import numpy as np
import soundfile as sf
from kokoro import KPipeline
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

# Load environment variables from .env file
load_dotenv()

MAX_TEXT_LENGTH = 500

# Set up production logging configuration
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("tts_api")

api = FastAPI(
    title="Speechy TTS API",
    description="Internal text-to-speech API running the Kokoro AI model",
    version="1.0.0"
)

# Secure CORS configuration for production environment
# Allows the Express backend (or direct frontend if needed) to communicate with FastAPI
frontend_origins = os.getenv("FRONTEND_ORIGINS", "https://f-oudghiri.dev,https://f-oudghiri.dev")
api.add_middleware(
    CORSMiddleware,
    allow_origins=[origin.strip() for origin in frontend_origins.split(",") if origin.strip()],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class TTSRequest(BaseModel):
    text: str
    language: str 

codes = {
     "a": "American English",
     "b": "British",
     "e": "Spanish",
     "f": "French",
     "h": "Hindi",
     "i": "Italian",
     "p": "Brazilian Portuguese",
}

voices = {
    "a": "af_bella",
    "b": "bf_emma",
    "f": "ff_siwis", 
    "e": "ef_dora", 
    "h": "hf_alpha", 
    "i": "if_sara", 
    "p": "pf_dora", 
}

pipelines = {}

# 🔴 PRODUCTION SECURITY: Strict container shutdown if HF_TOKEN is missing
hf_token = os.getenv("HF_TOKEN")
if not hf_token:
    logger.critical("CRITICAL ERROR: HF_TOKEN is missing from the environment variables!")
    raise RuntimeError("Missing HF_TOKEN. Unable to start the TTS API service.")
else:
    os.environ["HF_TOKEN"] = hf_token

def get_pipeline(language: str):
    if language not in pipelines:
        logger.info("Initializing Kokoro pipeline for target language: %s", codes.get(language))
        pipelines[language] = KPipeline(lang_code=language, repo_id="hexgrad/Kokoro-82M")
    return pipelines[language]

@api.get("/")
async def health_check():
    """Health check route for Nginx or Docker orchestrator monitoring"""
    return {"success": True, "message": "TTS API is running perfectly.", "status": "ok"}

@api.post("/tts")
async def synthesize_text(payload: TTSRequest):
    logger.info("New TTS synthesis request received. Target language code: %s", payload.language)
    text = payload.text.strip()
    language = (payload.language or "a").strip().lower()

    # Input safety validations
    if not text:
        raise HTTPException(status_code=400, detail="No text provided for TTS conversion.")
    if len(text) > MAX_TEXT_LENGTH:
        raise HTTPException(status_code=400, detail=f"Text is too long. Maximum allowed is {MAX_TEXT_LENGTH} characters.")
    if language not in codes:
        logger.warning("Unsupported language code rejected: %s", language)
        raise HTTPException(status_code=400, detail="Unsupported language code.")

    try:
        pipeline = get_pipeline(language)
        voice = voices.get(language)
        
        # Generate audio chunks using the AI model
        audio_chunks = [chunk for _, _, chunk in pipeline(text, voice, speed=0.8)]

        if not audio_chunks:
            logger.error("Kokoro model returned zero audio fragments for: %s", codes.get(language))
            raise HTTPException(status_code=500, detail="No audio generated by the AI model.")

        # Concatenate raw NumPy arrays into a single audio buffer
        audio = np.concatenate(audio_chunks)

        # Encode the raw audio data directly into RAM memory using MP3 format
        wav_buffer = io.BytesIO()
        sf.write(wav_buffer, audio, 24000, format="mp3")
        wav_buffer.seek(0)
        
        logger.info("MP3 audio stream successfully generated for language: %s", codes.get(language))

        # Stream the binary data directly back to the Express backend server
        return StreamingResponse(wav_buffer, media_type="audio/mpeg")
    
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception("Critical failure during audio synthesis processing for: %s", codes.get(language))
        raise HTTPException(status_code=500, detail="Internal server error during speech synthesis.") from exc
